research:
  description: >
    Usar todas as ferramentas disponíveis para encontrar informações sobre o tópico: {topic}.
  expected_output: >
    Uma análise teológica completa sobre o tópico, com as devidas fontes. É importante que a análise tenha os
    seguintes pontos:
    - {topic}
    - Classificação do tópico (Texto Bíblico, Tema, Dourtina, etc)
    - Como o tópico é tratado na Bíblia
    - Existem textos relacionados ao tópico. Caso seja um texto bíblico, exitem outros textos que falam sobre o mesmo assunto?
    - Contexto histórico
    - Análise hermenêutica
    - Difículdaes de interpretação
    - Aplicações práticas
    - Fontes

final_revision:
  description: >
    Avaliar se todos os pontos da pesquisa foram abordados e se a análise está correta. Os pontos são:
    - {topic}
    - Classificação do tópico (Texto Bíblico, Tema, Dourtina, etc)
    - Como o tópico é tratado na Bíblia
    - Existem textos relacionados ao tópico. Caso seja um texto bíblico, exitem outros textos que falam sobre o mesmo assunto?
    - Contexto histórico
    - Análise hermenêutica
    - Difículdaes de interpretação
    - Aplicações práticas
    - Fontes
  expected_output: >
    Uma análise teológica completa sobre o tópico, com as devidas fontes, com as devidas correções e melhorias, se necessários.


  
