research:
  description: >
    Buscar e citar livros de forma resumida. Apresente as ideias que estejam diretamente relacionada 
    ao tópico: {topic}.
  expected_output: >
    Citação dos livros encontrados com trecho do livro, nome do livro, autor e página.
    Apresentação dos argumentos encontrados sobre o tópico. Caso não exista relação apenas informe 
    que não há relação.

youtube_research:
  description: >
    Apresentar as ideias que o vídeo apresenta sobre o tópico: {topic}.
  expected_output: >
    Apresentação de forma completa com argumentos usados no vídeo sobre o tópico, com as 
    devidas fontes. Caso não exista relação apenas informe que não há relação.

final_revision:
  description: >
    Julgar se a saída dos especialistas está correta e se está falando diretamente do tópico.
  expected_output: >
    Tópico: {topic}
    Avalie se a saída dos especialistas está correta e se está falando diretamente do tópico. Se
    estiver correta e falando diretamente do tópico, apresente a saída. Caso contrário, informe que
    não há relação.


  
