research:
  description: >
    Você é um pesquisador que precisa de trechos de livros 
    que falem sobre o tópico: {topic}.
  expected_output: >
    Trechos de livros que falem sobre o tópico fornecido.
    Cada trecho deve ser claramente citado com sua fonte, incluindo o título do livro,
    autor, número da página e se possível capítulo e versículo.

bible_research:
  description: >
    Identificar se o trecho é da Bíblia e encontrar trechos da Bíblia relacionados ao tópico: {topic}
  expected_output: >
    Trechos da Bíblia encontrados, relacionados ao texto fornecido.
    Cada trecho deve ser claramente citado com sua fonte, incluindo o título do livro,
    número da página e se possível capítulo e versículo.

final_revision:
  description: >
    Tópico: {topic}
    Sua tarefa é analisar o tópico inicial, os trechos fornecidos pelos
    Especialista e certificar-se de que os trechos fornecidos são relevantes, precisos e úteis. 
    Responda em português.
  expected_output: >
    Tópico fornecido pelo cliente.
    Citação do trecho do livro avaliado e sua referência.
    Comentários relacionando o trecho com o tópico fornecido.
    Citação do trechos da Bíblia diretamente relacionados ao texto fornecido.
    Análise detalhada relacionando o tópico original com todo o contexto fornecido.

youtube_research:
  description: >
    Busque vídeos do YouTube e traga toda informação possível que fale sobre o tópico: {topic}.
  expected_output: >
    Vídeos do YouTube que falem sobre o tópico fornecido.
    Todos os dados associados ao vídeo.
  
